### ISSUE TITLE
Robeaux reimplemented on React

### ISSUE THREAD

**Issue by Tensho** [hybridgroup/artoo-site#17]
Currently official Artoo page has Angular dependency description for Robeaux, but it was reimplemented with React since 0.4.0. It seems to me this:
> Robeaux is powered by AngularJS, and provides a front-end to the API interface offered by Artoo

should be replaced with:

> Robeaux is powered by ReactJS, and provides a front-end to the API interface offered by Artoo.

**Comment by zankavrogin** [comment]
You're right @Tensho, I just updated the page. Thanks!
