### ISSUE TITLE
Link to AR.Drone driver broken

### ISSUE THREAD

**Issue by ZimbiX** [hybridgroup/artoo-site#18]
I would have fixed this and submitted a pull request, but I've had a look through the code, and I'm not sure where's best for this fix to be made, given that the link, image, and title are all generated from one value.

Basically, down the bottom of:

http://artoo.io/documentation/platforms/ardrone/

there's an image link to:

http://artoo.io/documentation/drivers/ardrone-flight

which should instead be:

http://artoo.io/documentation/drivers/ardrone

The driver seems to be called "AR.Drone" in some places, and "AR.Drone Flight" in others...

**Comment by stewart** [comment]
Closing, as this issue was fixed by #19. Thanks for the heads-up!

**Comment by ZimbiX** [comment]
Hah, that looks like it was easy. No problem
